### ISSUE TITLE
Complaints are over 9000

### ISSUE THREAD

**Issue by DanielHauge** [HackerNews-lsd2017/fe-hacker-news#18]
The front end looks a tad bit strange. There's 10 stories, all of them is undefined, undefined time ago, and undefined comments. My customers are complaining they can't see their stories and comments, the complains are piling high, more than 10.000 complaints at current given time.
http://46.101.28.25:8080/latest

**Comment by WillVill** [comment]
This issue is being closed due to the fixes having been implemented
